version: '3'
services:
  pgsql:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: desafio_modulo_3
    volumes:
      - ./sql/initiate_database.sql:/docker-entrypoint-initdb.d/initiate_database.sql
      - ./sql/metabase-dump.sql:/docker-entrypoint-initdb.d/metabase-dump.sql
      - ./dataset/survey_results_public.csv:/home/survey_results_public.csv
    
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - '8080:8080'
    depends_on:
      - pgsql
  
  metabase:
    image: metabase/metabase:latest
    restart: always
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: postgres
      MB_DB_PORT: 5432
      MB_DB_USER: postgres
      MB_DB_PASS: desafio_modulo_3
      MB_DB_HOST: pgsql
      JAVA_TIMEZONE: America/Sao_Paulo
    ports: 
      - "3000:3000"
    depends_on:
      - pgsql
