create table if not exists survey_results_public(
    "Id" serial, 
    "Respondent" text,
    "MainBranch" text,
    "Hobbyist" text,
    "Age" text,
    "Age1stCode" text,
    "CompFreq" text,
    "CompTotal" text,
    "ConvertedComp" text,
    "Country" text,
    "CurrencyDesc" text,
    "CurrencySymbol" text,
    "DatabaseDesireNextYear" text,
    "DatabaseWorkedWith" text,
    "DevType" text,
    "EdLevel" text,
    "Employment" text,
    "Ethnicity" text,
    "Gender" text,
    "JobFactors" text,
    "JobSat" text,
    "JobSeek" text,
    "LanguageDesireNextYear" text,
    "LanguageWorkedWith" text,
    "MiscTechDesireNextYear" text,
    "MiscTechWorkedWith" text,
    "NEWCollabToolsDesireNextYear" text,
    "NEWCollabToolsWorkedWith" text,
    "NEWDevOps" text,
    "NEWDevOpsImpt" text,
    "NEWEdImpt" text,
    "NEWJobHunt" text,
    "NEWJobHuntResearch" text,
    "NEWLearn" text,
    "NEWOffTopic" text,
    "NEWOnboardGood" text,
    "NEWOtherComms" text,
    "NEWOvertime" text,
    "NEWPurchaseResearch" text,
    "NEWPurpleLink" text,
    "NEWSOSites" text,
    "NEWStuck" text,
    "OpSys" text,
    "OrgSize" text,
    "PlatformDesireNextYear" text,
    "PlatformWorkedWith" text,
    "PurchaseWhat" text,
    "Sexuality" text,
    "SOAccount" text,
    "SOComm" text,
    "SOPartFreq" text,
    "SOVisitFreq" text,
    "SurveyEase" text,
    "SurveyLength" text,
    "Trans" text,
    "UndergradMajor" text,
    "WebframeDesireNextYear" text,
    "WebframeWorkedWith" text,
    "WelcomeChange" text,
    "WorkWeekHrs" text,
    "YearsCode" text,
    "YearsCodePro" text,

    primary key ("Id")
);

COPY survey_results_public(
    "Respondent",
    "MainBranch",
    "Hobbyist",
    "Age",
    "Age1stCode",
    "CompFreq",
    "CompTotal",
    "ConvertedComp",
    "Country",
    "CurrencyDesc",
    "CurrencySymbol",
    "DatabaseDesireNextYear",
    "DatabaseWorkedWith",
    "DevType",
    "EdLevel",
    "Employment",
    "Ethnicity",
    "Gender",
    "JobFactors",
    "JobSat",
    "JobSeek",
    "LanguageDesireNextYear",
    "LanguageWorkedWith",
    "MiscTechDesireNextYear",
    "MiscTechWorkedWith",
    "NEWCollabToolsDesireNextYear",
    "NEWCollabToolsWorkedWith",
    "NEWDevOps",
    "NEWDevOpsImpt",
    "NEWEdImpt",
    "NEWJobHunt",
    "NEWJobHuntResearch",
    "NEWLearn",
    "NEWOffTopic",
    "NEWOnboardGood",
    "NEWOtherComms",
    "NEWOvertime",
    "NEWPurchaseResearch",
    "NEWPurpleLink",
    "NEWSOSites",
    "NEWStuck",
    "OpSys",
    "OrgSize",
    "PlatformDesireNextYear",
    "PlatformWorkedWith",
    "PurchaseWhat",
    "Sexuality",
    "SOAccount",
    "SOComm",
    "SOPartFreq",
    "SOVisitFreq",
    "SurveyEase",
    "SurveyLength",
    "Trans",
    "UndergradMajor",
    "WebframeDesireNextYear",
    "WebframeWorkedWith",
    "WelcomeChange",
    "WorkWeekHrs",
    "YearsCode",
    "YearsCodePro"
)
FROM '/home/survey_results_public.csv'
DELIMITER ','
CSV HEADER;
